# Generated by Django 4.1.2 on 2022-10-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_comentarios_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ong',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='ong',
            name='image',
            field=models.ImageField(null=True, upload_to='ongs'),
        ),
    ]
