# Generated by Django 4.1.2 on 2022-10-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_ong_whatsapp_ong_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ong',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
