# Generated by Django 4.1.2 on 2022-10-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ong_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='midia',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
