# Generated by Django 4.1.2 on 2022-10-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_midia_midia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='senha',
            field=models.CharField(default='aaa', max_length=252),
            preserve_default=False,
        ),
    ]
