# Generated by Django 4.1.2 on 2022-10-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ong_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='descricao',
            field=models.CharField(default='sem descrição', max_length=1000),
            preserve_default=False,
        ),
    ]
