# Generated by Django 4.1.2 on 2022-10-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ong',
            name='senha',
        ),
        migrations.AddField(
            model_name='ong',
            name='password',
            field=models.CharField(default='senha', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ong',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
