# Generated by Django 4.1.2 on 2022-10-14 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_ong_options_alter_ong_managers_ong_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ong',
            name='uf',
        ),
    ]
