# Generated by Django 4.1.2 on 2022-10-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_ong_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='raw_password',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
