# Generated by Django 4.1.2 on 2022-10-15 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ong_raw_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ong',
            name='raw_password',
        ),
    ]
